targets:
  $default:
    builders:
      # gql_build|schema_builder:
      #   enabled: true
      # gql_build|ast_builder:
      #   enabled: true
      # gql_build|data_builder:
      #   enabled: true
      #   options:
      #     schema: satujuta_gql_client|lib/schema/schema.graphql
      #     output_dir: generated
      # gql_build|var_builder:
      #   enabled: true
      #   options:
      #     schema: satujuta_gql_client|lib/schema/schema.graphql
      #     output_dir: generated
      # gql_build|serializer_builder:
      #   enabled: true
      #   options:
      #     schema: satujuta_gql_client|lib/schema/schema.graphql
      #     output_dir: generated
      # ferry_generator|graphql_builder:
      #   enabled: true
      #   options:
      #     schema: satujuta_gql_client|lib/schema/schema.graphql
      #     output_dir: generated
      # ferry_generator|serializer_builder:
      #   enabled: true
      #   options:
      #     schema: satujuta_gql_client|lib/schema/schema.graphql
      #     output_dir: generated
      graphql_codegen:
        options:
          assetsPath: lib/**
          outputDirectory: generated
          clients:
            - graphql_flutter
